// -------------------------------------------------------------
// 
// File Name: D:\B01-Study\MATLAB_Projects\Projects\Horner_poly\codegen\Horner_poly_expansion\hdlsrc\Horner_poly_expansion_fixpt_tb.v
// Created: 2024-04-03 21:20:39
// 
// Generated by MATLAB 23.2, MATLAB Coder 23.2 and HDL Coder 23.2
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Horner_poly_expansion_fixpt_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Horner_poly_expansion_fixpt_tb;



  reg  clk;
  reg  reset;
  wire enb;
  wire y_re_done;  // ufix1
  wire rdEnb;
  wire y_re_done_enb;  // ufix1
  reg [11:0] y_re_addr;  // ufix12
  wire y_re_active;  // ufix1
  wire [11:0] x_in_addr_delay;  // ufix12
  wire tb_enb;
  reg signed [31:0] fp_x_in_im;  // sfix32
  reg signed [13:0] rawData_x_in_im;  // sfix14_En14
  reg signed [31:0] status_x_in_im;  // sfix32
  reg signed [13:0] holdData_x_in_im;  // sfix14_En14
  reg signed [13:0] x_in_im_offset;  // sfix14_En14
  wire signed [13:0] x_in_im;  // sfix14_En14
  reg [11:0] x_in_addr;  // ufix12
  wire x_in_active;  // ufix1
  wire x_in_enb;  // ufix1
  reg signed [31:0] fp_x_in_re;  // sfix32
  reg signed [13:0] rawData_x_in_re;  // sfix14_En14
  reg signed [31:0] status_x_in_re;  // sfix32
  reg signed [13:0] holdData_x_in_re;  // sfix14_En14
  reg signed [13:0] x_in_re_offset;  // sfix14_En14
  wire signed [13:0] x_in_re;  // sfix14_En14
  reg  check1_done;  // ufix1
  wire snkDonen;
  wire resetn;
  wire ce_out;
  wire signed [13:0] y_re;  // sfix14_En11
  wire signed [13:0] y_im;  // sfix14_En11
  wire y_re_enb;  // ufix1
  wire y_re_lastAddr;  // ufix1
  wire [11:0] y_re_addr_delay_1;  // ufix12
  reg signed [31:0] fp_y_re_expected;  // sfix32
  reg signed [13:0] y_re_expected;  // sfix14_En11
  reg signed [31:0] status_y_re_expected;  // sfix32
  wire signed [13:0] y_re_ref;  // sfix14_En11
  reg  y_re_testFailure;  // ufix1
  reg signed [31:0] fp_y_im_expected;  // sfix32
  reg signed [13:0] y_im_expected;  // sfix14_En11
  reg signed [31:0] status_y_im_expected;  // sfix32
  wire signed [13:0] y_im_ref;  // sfix14_En11
  reg  y_im_testFailure;  // ufix1
  wire testFailure;  // ufix1


  assign y_re_done_enb = y_re_done & rdEnb;



  assign y_re_active = y_re_addr != 12'b101110110111;



  // Data source for x_in_im
  initial
    begin : x_in_im_fileread
      fp_x_in_im = $fopen("x_in_im.dat", "r");
      status_x_in_im = $rewind(fp_x_in_im);
    end

  always @(x_in_addr_delay, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_x_in_im <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_x_in_im = $fscanf(fp_x_in_im, "%h", rawData_x_in_im);
      end
    end

  // holdData reg for x_in
  always @(posedge clk or posedge reset)
    begin : stimuli_x_in
      if (reset) begin
        holdData_x_in_im <= 14'bx;
      end
      else begin
        holdData_x_in_im <= rawData_x_in_im;
      end
    end

  always @(rawData_x_in_im or rdEnb)
    begin : stimuli_x_in_1
      if (rdEnb == 1'b0) begin
        x_in_im_offset <= holdData_x_in_im;
      end
      else begin
        x_in_im_offset <= rawData_x_in_im;
      end
    end

  assign #2 x_in_im = x_in_im_offset;

  assign x_in_active = x_in_addr != 12'b101110110111;



  assign x_in_enb = x_in_active & (rdEnb & tb_enb);



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 2999
  always @(posedge clk or posedge reset)
    begin : x_in_process
      if (reset == 1'b1) begin
        x_in_addr <= 12'b000000000000;
      end
      else begin
        if (x_in_enb) begin
          if (x_in_addr >= 12'b101110110111) begin
            x_in_addr <= 12'b000000000000;
          end
          else begin
            x_in_addr <= x_in_addr + 12'b000000000001;
          end
        end
      end
    end



  assign #1 x_in_addr_delay = x_in_addr;

  // Data source for x_in_re
  initial
    begin : x_in_re_fileread
      fp_x_in_re = $fopen("x_in_re.dat", "r");
      status_x_in_re = $rewind(fp_x_in_re);
    end

  always @(x_in_addr_delay, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_x_in_re <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_x_in_re = $fscanf(fp_x_in_re, "%h", rawData_x_in_re);
      end
    end

  // holdData reg for x_in
  always @(posedge clk or posedge reset)
    begin : stimuli_x_in_2
      if (reset) begin
        holdData_x_in_re <= 14'bx;
      end
      else begin
        holdData_x_in_re <= rawData_x_in_re;
      end
    end

  always @(rawData_x_in_re or rdEnb)
    begin : stimuli_x_in_3
      if (rdEnb == 1'b0) begin
        x_in_re_offset <= holdData_x_in_re;
      end
      else begin
        x_in_re_offset <= rawData_x_in_re;
      end
    end

  assign #2 x_in_re = x_in_re_offset;

  assign snkDonen =  ~ check1_done;



  assign resetn =  ~ reset;



  assign tb_enb = resetn & snkDonen;



  assign rdEnb = (check1_done == 1'b0 ? tb_enb :
              1'b0);



  assign #2 enb = rdEnb;

  initial
    begin : reset_gen
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (2);
      reset <= 1'b0;
    end

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (check1_done == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  Horner_poly_expansion_fixpt u_Horner_poly_expansion_fixpt (.clk(clk),
                                                             .reset(reset),
                                                             .clk_enable(enb),
                                                             .x_in_re(x_in_re),  // sfix14_En14
                                                             .x_in_im(x_in_im),  // sfix14_En14
                                                             .ce_out(ce_out),
                                                             .y_re(y_re),  // sfix14_En11
                                                             .y_im(y_im)  // sfix14_En11
                                                             );

  assign y_re_enb = ce_out & y_re_active;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 2999
  always @(posedge clk or posedge reset)
    begin : y_process
      if (reset == 1'b1) begin
        y_re_addr <= 12'b000000000000;
      end
      else begin
        if (y_re_enb) begin
          if (y_re_addr >= 12'b101110110111) begin
            y_re_addr <= 12'b000000000000;
          end
          else begin
            y_re_addr <= y_re_addr + 12'b000000000001;
          end
        end
      end
    end



  assign y_re_lastAddr = y_re_addr >= 12'b101110110111;



  assign y_re_done = y_re_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_1
      if (reset) begin
        check1_done <= 0;
      end
      else begin
        if (y_re_done_enb) begin
          check1_done <= y_re_done;
        end
      end
    end

  assign #1 y_re_addr_delay_1 = y_re_addr;

  // Data source for y_re_expected
  initial
    begin : y_re_expected_fileread
      fp_y_re_expected = $fopen("y_re_expected.dat", "r");
      status_y_re_expected = $rewind(fp_y_re_expected);
    end

  always @(y_re_addr_delay_1, ce_out, tb_enb)
    begin
      if (tb_enb == 0) begin
        y_re_expected <= 14'bx;
      end
      else if (ce_out == 1) begin
        status_y_re_expected = $fscanf(fp_y_re_expected, "%h", y_re_expected);
      end
    end

  assign y_re_ref = y_re_expected;

  always @(posedge clk or posedge reset)
    begin : y_re_checker
      if (reset == 1'b1) begin
        y_re_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && y_re !== y_re_ref) begin
          y_re_testFailure <= 1'b1;
          $display("ERROR in y_re at time %t : Expected '%h' Actual '%h'", $time, y_re_ref, y_re);
        end
      end
    end

  // Data source for y_im_expected
  initial
    begin : y_im_expected_fileread
      fp_y_im_expected = $fopen("y_im_expected.dat", "r");
      status_y_im_expected = $rewind(fp_y_im_expected);
    end

  always @(y_re_addr_delay_1, ce_out, tb_enb)
    begin
      if (tb_enb == 0) begin
        y_im_expected <= 14'bx;
      end
      else if (ce_out == 1) begin
        status_y_im_expected = $fscanf(fp_y_im_expected, "%h", y_im_expected);
      end
    end

  assign y_im_ref = y_im_expected;

  always @(posedge clk or posedge reset)
    begin : y_im_checker
      if (reset == 1'b1) begin
        y_im_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && y_im !== y_im_ref) begin
          y_im_testFailure <= 1'b1;
          $display("ERROR in y_im at time %t : Expected '%h' Actual '%h'", $time, y_im_ref, y_im);
        end
      end
    end

  assign testFailure = y_re_testFailure | y_im_testFailure;



  always @(posedge clk)
    begin : completed_msg
      if (check1_done == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // Horner_poly_expansion_fixpt_tb

